version: '3.1'

services:
  db:
    image: mysql
    container_name: bank
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - bank_transactions:/var/lib/mysql

volumes:
  bank_transactions: